# Generated by Django 2.1.7 on 2022-03-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Member')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
