# Generated by Django 2.1.7 on 2022-03-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
