# Generated by Django 4.0.3 on 2022-03-28 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image_url', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'db_table': 'Todo',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(default=datetime.datetime.now)),
                ('finish_at', models.DateField(default=datetime.datetime.now)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
