# Generated by Django 2.1.7 on 2022-06-04 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
            options={
                'db_table': 'Application',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
            options={
                'db_table': 'Board',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_manager', models.BooleanField(default=False)),
                ('field', models.CharField(max_length=100)),
                ('image_url', models.ImageField(blank=True, upload_to='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Club_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'club_info',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('written_at', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('from_member_name', models.CharField(max_length=100)),
                ('to_member_name', models.CharField(max_length=100)),
                ('written_at', models.DateField(auto_now_add=True)),
                ('reference_id', models.IntegerField(blank=True, default=0)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Letter',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_at', models.DateField(default=datetime.datetime.now)),
                ('finish_at', models.DateField(default=datetime.datetime.now)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('state', models.TextField(blank=True, max_length=100, null=True)),
                ('club_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('club_name', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'Todo',
            },
        ),
    ]
