# Generated by Django 2.1.7 on 2022-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('from_member_name', models.CharField(max_length=100)),
                ('to_member_name', models.CharField(max_length=100)),
                ('written_at', models.DateField(auto_now_add=True)),
                ('reference_id', models.IntegerField(blank=True, default=0)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Letter',
            },
        ),
    ]
