# Generated by Django 2.1.7 on 2022-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_schedule_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
