# Generated by Django 2.1.7 on 2022-06-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_schedule_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='field',
        ),
        migrations.AddField(
            model_name='club_info',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
